src/objects/Expense__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Expenses</relationshipLabel>
        <relationshipName>Expenses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Expense_Date__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <label>Expense Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Subject__c</fullName>
        <label>Subject</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Home</fullName>
                </value>
                <value>
                    <fullName>Bills</fullName>
                </value>
                <value>
                    <fullName>Education</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Expense</label>
    <nameField>
        <displayFormat>EX-{0000}</displayFormat>
        <label>Expense Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ExpenseListController.cls
public class ExpenseListController {
    public static final String SPACE = ' ';
    public static final String MAIN_QUERY = 'SELECT Id, Subject__c, Amount__c, Account__r.Name, Description__c, Expense_Date__c, Type__c FROM Expense__c';
    public static final String ORDER_BY = 'ORDER BY Expense_Date__c DESC';
    public static final String STRING_WHERE_CLAUSE = 'WHERE Subject__c like :likeClause OR Description__c like :likeClause';
    public static final String DECIMAL_WHERE_CLAUSE = 'WHERE Amount__c = :searchAmountDecimal OR Subject__c like :likeClause OR Description__c like :likeClause';

    @AuraEnabled
    public static List<Expense__c > getMyExpenses() {
        return Database.query(MAIN_QUERY + SPACE + ORDER_BY);
    }

    @AuraEnabled
    public static List<Expense__c > getMyExpensesSearch(String inputString) {
        String finalQuery;
        String likeClause = '%' + inputString + '%';
        Decimal searchAmountDecimal;

        try {
            searchAmountDecimal = Decimal.valueOf(inputString);
            finalQuery =    MAIN_QUERY + SPACE + 
                            DECIMAL_WHERE_CLAUSE + SPACE + 
                            ORDER_BY;
        } catch (Exception e) {
            finalQuery =    MAIN_QUERY + SPACE + 
                            STRING_WHERE_CLAUSE + SPACE + 
                            ORDER_BY;
        }

        return Database.query(finalQuery);
    }
}